### ISSUE TITLE
Error when insterting a 5

### ISSUE THREAD

**Issue by battlejoose** [coinmastersguild/bankless-v2#2]
nected jpqJRBKhk_gGgNtWAAAD  user:  undefined
 2023-12-19 18:34:03.327Z INFO [undefined:undefined:undefined] create Buy!
 2023-12-19 18:34:03.527Z INFO [undefined:undefined:undefined]  | Bankless-Backend |  | set_session_buy |  CURR
ENT_SESSION:  {
  sessionId: 'f5J1gTB46XgPt9tmMhiZ8Q',
  address: '0x4fc91C49b42ea98A934e1160b9FD46ab21f9477C',
  type: 'buy'
}
 2023-12-19 18:34:16.689Z INFO [undefined:undefined:undefined]  | Bankless-Backend |  | onStartAcceptor |  READ
_NOTE { value: 100, country_code: 'USD' }
message:  {"amount":1,"asset":"USD","event":"payments"}
message:  {"amount":"1","asset":"USD","sessionId":"f5J1gTB46XgPt9tmMhiZ8Q","event":"payments"}
 2023-12-19 18:34:46.000Z INFO [undefined:undefined:undefined]  | Bankless-Backend |  | onStartAcceptor |  READ
_NOTE { value: 500, country_code: 'USD' }
C:\Users\Administrator\Downloads\bankless-v2-master\backend\dist\bankless.js:144
                            throw new Error(JSON.stringify(result));
                                  ^

Error: {"success":false,"status":"COMMAND_CANNOT_BE_PROCESSED","command":"REJECT_BANKNOTE","info":{}}
    at SSP.<anonymous> (C:\Users\Administrator\Downloads\bankless-v2-master\backend\dist\bankless.js:144:35)   
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Administrator\Downloads\bankless-v2-master\backend\dist\bankless.js:16:58)

Node.js v20.10.0

Process finished with exit code 1

**Comment by BitHighlander** [comment]
resolved https://github.com/BitHighlander/bankless-v2/commit/7022bd43f2f07a29ee4cba9e129f70435d344178
